---
# file: playbook.yml
#   Shortcut to run install tasks on the localhost without setting up an inventory.
- hosts: localhost
  connection: local
  vars:
    galaxy_config_style: yaml
    galaxy_layout: legacy-improved
    galaxy_server_dir: /galaxy/server
    galaxy_commit_id: release_19.05
    galaxy_repo: https://github.com/telukir/galaxy.git
    galaxy_clone_depth: 1
    galaxy_virtualenv_command: /usr/bin/python2 -m virtualenv
    pip_extra_args: "--no-cache-dir --compile"
    galaxy_client_make_target: client-production
    galaxy_config_files:
      - src: files/job_conf.xml
        dest: "{{ galaxy_server_dir }}/config/job_conf.xml"
      - src: files/welcome.html
        dest: "{{ galaxy_server_dir }}/static/welcome.html"
    galaxy_config:
      uwsgi:
        virtualenv: "{{ galaxy_server_dir }}/.venv"
        pythonpath: "{{ galaxy_server_dir }}/lib"
        module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
        http: 0.0.0.0:8080
        static-map:
          - /static/style={{ galaxy_server_dir }}/static/style/blue
          - /static={{ galaxy_server_dir }}/static
        thunder-lock: true
        buffer-size: 16384
        offload-threads: 2
        processes: 1
        threads: 4
        die-on-term: true
        master: true
        hook-master-start:
          - unix_signal:2 gracefully_kill_them_all
          - unix_signal:15 gracefully_kill_them_all
        enable-threads: true
        py-call-osafterfork: true
      galaxy:
        database_connection: postgresql://galaxydbuser:42@gpsql/galaxy
  roles:
    - galaxy
